In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Reading data and storing it in train_data and test_data

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data.info()
print('-------------------------')
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4357336 entries, 0 to 4357335
Data columns (total 26 columns):
Id                 int64
groupId            int64
matchId            int64
assists            int64
boosts             int64
damageDealt        float64
DBNOs              int64
headshotKills      int64
heals              int64
killPlace          int64
killPoints         int64
kills              int64
killStreaks        int64
longestKill        float64
maxPlace           int64
numGroups          int64
revives            int64
rideDistance       float64
roadKills          int64
swimDistance       float64
teamKills          int64
vehicleDestroys    int64
walkDistance       float64
weaponsAcquired    int64
winPoints          int64
winPlacePerc       float64
dtypes: float64(6), int64(20)
memory usage: 864.3 MB
-------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1867913 entries, 0 to 1867912
Data columns (total 25 columns):
Id                 int64
groupId 

In [4]:
print(train_data.shape)
print(test_data.shape)

(4357336, 26)
(1867913, 25)


we can see that there are only 25 columns in the test data and 'winPlacePerc' is the one needed tho be predicted

In [5]:
train_df = pd.DataFrame(train_data)

In [6]:
test_df = pd.DataFrame(test_data)

In [7]:
train_df.isnull().sum()

Id                 0
groupId            0
matchId            0
assists            0
boosts             0
damageDealt        0
DBNOs              0
headshotKills      0
heals              0
killPlace          0
killPoints         0
kills              0
killStreaks        0
longestKill        0
maxPlace           0
numGroups          0
revives            0
rideDistance       0
roadKills          0
swimDistance       0
teamKills          0
vehicleDestroys    0
walkDistance       0
weaponsAcquired    0
winPoints          0
winPlacePerc       0
dtype: int64

In [8]:
test_df.isnull().sum()

Id                 0
groupId            0
matchId            0
assists            0
boosts             0
damageDealt        0
DBNOs              0
headshotKills      0
heals              0
killPlace          0
killPoints         0
kills              0
killStreaks        0
longestKill        0
maxPlace           0
numGroups          0
revives            0
rideDistance       0
roadKills          0
swimDistance       0
teamKills          0
vehicleDestroys    0
walkDistance       0
weaponsAcquired    0
winPoints          0
dtype: int64

we see there are no null values and also all the values are in numerical values hence preprocessing of data is already done.
Now performing EDA will give us basic idea about the data.

In [9]:
train_df.head()

Id  groupId  matchId  assists  boosts  damageDealt  DBNOs  headshotKills  \
0   0       24        0        0       5       247.30      2              0   
1   1   440875        1        1       0        37.65      1              1   
2   2   878242        2        0       1        93.73      1              0   
3   3  1319841        3        0       0        95.88      0              0   
4   4  1757883        4        0       1         0.00      0              0   

   heals  killPlace      ...       revives  rideDistance  roadKills  \
0      4         17      ...             1         591.3          0   
1      0         45      ...             0           0.0          0   
2      2         54      ...             1           0.0          0   
3      0         86      ...             0           0.0          0   
4      1         58      ...             0           0.0          0   

   swimDistance  teamKills  vehicleDestroys  walkDistance  weaponsAcquired  \
0           0.0          0                0        782.40                4   
1           0.0          0                0        119.60                3   
2           0.0          0                0       3248.00                5   
3           0.0          0                0         21.49                1   
4           0.0          0                0        640.80                4   

   winPoints  winPlacePerc  
0       1458        0.8571  
1       1511        0.0400  
2       1583        0.7407  
3       1489        0.1146  
4       1475        0.5217  

[5 rows x 26 columns]

In [10]:
#sns.pairplot(train_df, vars = ['damageDealt','winPlacePerc'], size=5)
# could be seen that higher damage dealt is directly related to win

In [11]:
#df= train_df.copy()
#corr = df.drop('winPlacePerc', axis=1).corr() 
#plt.figure(figsize=(12, 10))

#sns.heatmap(corr[(corr >= 0.5) | (corr <= -0.4)], 
           # cmap='viridis', vmax=1.0, vmin=-1.0, linewidths=0.1,
            #annot=True, annot_kws={"size": 8}, square=True);

In [12]:
 train_df.corr()

Id   groupId   matchId   assists    boosts  \
Id               1.000000  0.001050  0.006400 -0.032262 -0.015682   
groupId          0.001050  1.000000  0.090547  0.000966 -0.000318   
matchId          0.006400  0.090547  1.000000  0.000825  0.000164   
assists         -0.032262  0.000966  0.000825  1.000000  0.312516   
boosts          -0.015682 -0.000318  0.000164  0.312516  1.000000   
damageDealt     -0.034080  0.000549  0.000806  0.421591  0.525806   
DBNOs           -0.031732  0.001050  0.000346  0.336822  0.354167   
headshotKills   -0.018974  0.000195  0.000543  0.213781  0.342132   
heals           -0.017770 -0.000606 -0.001269  0.254413  0.543742   
killPlace        0.046803  0.000408 -0.000847 -0.299240 -0.540404   
killPoints      -0.003405 -0.001800 -0.003744  0.103351  0.150880   
kills           -0.031724  0.000635  0.000907  0.332530  0.501028   
killStreaks     -0.022485  0.000551 -0.000126  0.247418  0.403381   
longestKill     -0.016866 -0.000330  0.000054  0.259494  0.423239   
maxPlace         0.041232 -0.001978  0.002195 -0.146551 -0.017485   
numGroups        0.041857 -0.002078  0.002424 -0.146017 -0.017577   
revives         -0.013686  0.000147 -0.000459  0.212880  0.262386   
rideDistance    -0.014290 -0.002865  0.000064  0.095768  0.308582   
roadKills       -0.001939 -0.000300 -0.000660  0.011365  0.036168   
swimDistance    -0.000135  0.000053  0.000054  0.028043  0.115051   
teamKills        0.001336 -0.000727 -0.000780  0.004533 -0.001643   
vehicleDestroys -0.001944 -0.000568 -0.000296  0.042473  0.070621   
walkDistance    -0.014920  0.000046 -0.000823  0.286199  0.643818   
weaponsAcquired -0.033340  0.001101  0.001212  0.254903  0.383074   
winPoints       -0.011046 -0.000419 -0.000458  0.074668  0.121879   
winPlacePerc    -0.018157 -0.000239  0.000423  0.304642  0.618075   

                 damageDealt     DBNOs  headshotKills     heals  killPlace  \
Id                 -0.034080 -0.031732      -0.018974 -0.017770   0.046803   
groupId             0.000549  0.001050       0.000195 -0.000606   0.000408   
matchId             0.000806  0.000346       0.000543 -0.001269  -0.000847   
assists             0.421591  0.336822       0.213781  0.254413  -0.299240   
boosts              0.525806  0.354167       0.342132  0.543742  -0.540404   
damageDealt         1.000000  0.776050       0.618815  0.381556  -0.674264   
DBNOs               0.776050  1.000000       0.512157  0.289970  -0.561372   
headshotKills       0.618815  0.512157       1.000000  0.229129  -0.480663   
heals               0.381556  0.289970       0.229129  1.000000  -0.394194   
killPlace          -0.674264 -0.561372      -0.480663 -0.394194   1.000000   
killPoints          0.241333  0.197638       0.157129  0.082882  -0.157645   
kills               0.886165  0.754374       0.683723  0.344077  -0.728624   
killStreaks         0.702178  0.656239       0.524479  0.287548  -0.809442   
longestKill         0.543357  0.430523       0.436106  0.279934  -0.520010   
maxPlace           -0.046423 -0.252001       0.004057 -0.067800   0.041661   
numGroups          -0.046156 -0.250742       0.003726 -0.068220   0.042314   
revives             0.282945  0.294708       0.171552  0.249880  -0.282154   
rideDistance        0.136733  0.078993       0.069235  0.280616  -0.204666   
roadKills           0.054155  0.034283       0.015664  0.026778  -0.048464   
swimDistance        0.042669  0.020948       0.032103  0.082417  -0.092159   
teamKills           0.057412  0.077216       0.012143  0.012462  -0.030694   
vehicleDestroys     0.066731  0.042757       0.031140  0.054701  -0.055524   
walkDistance        0.397477  0.269110       0.255772  0.432847  -0.580114   
weaponsAcquired     0.362554  0.266989       0.229016  0.313044  -0.469039   
winPoints           0.110597  0.084146       0.063710  0.079382  -0.137097   
winPlacePerc        0.438552  0.279475       0.278705  0.427986  -0.708314   

                     ...        revives  rideDistanc

In [13]:
#train_df.plot(x="kills",y="damageDealt", kind="scatter", figsize = (15,10))

In [14]:
avg = train_df['headshotKills'].mean()
ninety = train_df['headshotKills'].quantile(0.95)
highest = train_df['headshotKills'].max()

print('Average no. of headshots: {0} \nNo. of headshots of 95% of people: {1} \nMax Headshots: {2}'.format(avg, ninety, highest))

Average no. of headshots: 0.23858660429216383 
No. of headshots of 95% of people: 1.0 
Max Headshots: 26


In [15]:
avg = train_df['assists'].mean()
ninety = train_df['assists'].quantile(0.95)
highest = train_df['assists'].max()

In [16]:
print('Average no. of assists: {0} \nNo. of assists of 95% of people: {1} \nMax assists: {2}'.format(avg, ninety, highest))

Average no. of assists: 0.26563202837697164 
No. of assists of 95% of people: 1.0 
Max assists: 20


In [17]:
#plt.figure(figsize = (15, 10))
#sns.countplot(train_df['assists'].sort_values())
#plt.title('Assist Count')
#plt.show()

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
  from sklearn.model_selection import train_test_split

In [20]:
X = train_df.iloc[:,:25]
y = train_df['winPlacePerc']

In [21]:
lm = LinearRegression()

In [22]:
 X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [23]:
lm.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
y_pred= lm.predict(X_test)

In [25]:
pred = lm.predict(test_df)

In [26]:
pred

array([0.35283721, 0.50123566, 0.17067465, ..., 0.03249703, 0.46778697,
       0.33619858])

In [27]:
submission = pd.DataFrame.from_dict(data={'Id': test_df['Id'], 'winPlacePerc': pred})

submission.head()

submission.to_csv("submission.csv", )

In [28]:
train_proc = train_df.copy()

In [29]:
train_proc['winPlacePerc'] = np.where(train_proc.winPlacePerc>0.5, 1, 0)

In [30]:
X1 = train_proc.iloc[:,:25]
y1= train_proc['winPlacePerc']

In [31]:
lm.coef_

array([ 2.02433451e-09,  1.50709095e-10, -7.70284566e-09,  1.83695052e-02,
        1.54453277e-02,  4.11656471e-05, -3.47163125e-03, -2.77985259e-03,
        8.96240542e-04, -7.20168189e-03, -3.58519489e-05, -1.08226197e-02,
       -1.34095714e-01, -3.59906119e-05, -7.22489040e-03,  8.70285717e-03,
        1.63912002e-02,  3.53739161e-06,  1.15426031e-03,  1.72998268e-04,
       -3.13154376e-02, -3.24983124e-03,  1.21753537e-04,  1.12015318e-02,
        2.31735325e-04])

In [32]:
lm.score(X_test,Y_test)

0.8065050362326408

In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)


In [34]:
 X_train_p, X_test_p, Y_train_P, Y_test_p = train_test_split(X1, y1, test_size= 0.2, random_state= 0)

In [35]:
classifier.fit(X_train_p,Y_train_P)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
    y_pred_p= classifier.predict(X_test_p)

In [37]:
y_prob = classifier.predict_proba(test_df)

In [38]:
y_prob_df = pd.DataFrame(y_prob)

In [39]:
y_win = y_prob_df.loc[:,1]

In [42]:
y_win.shape

(1867913,)

In [43]:
y_win_arr = y_win.values

In [44]:
submission = pd.DataFrame.from_dict(data={'Id': test_df['Id'], 'winPlacePerc': y_win_arr})



In [46]:
import statsmodels.api as sm

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test_p, y_pred_p)
print(confusion_matrix)


[[441446  34097]
 [ 62021 333904]]


In [49]:
from sklearn.metrics import classification_report
print(classification_report(Y_test_p, y_pred_p))

             precision    recall  f1-score   support

          0       0.88      0.93      0.90    475543
          1       0.91      0.84      0.87    395925

avg / total       0.89      0.89      0.89    871468

